// Supabase Configuration
const supabaseUrl = 'https://kldekjrpottsqebueojg.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsZGVranJwb3R0c3FlYnVlb2pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTc4NTcsImV4cCI6MjA2NzYzMzg1N30.aYCWfbhliWM3yQRyZUDL59IgMOWklwa0ZA4QOSdyLh0';
const supabase = window.supabase?.createClient ? window.supabase.createClient(supabaseUrl, supabaseKey) : null;

// Stripe Configuration
const stripe = Stripe('pk_live_51RVvveJLuu6b086bkMWivsLTKUamDhivaYv3ObKeMpV2kHSjCKuYE3sijENdGWISCsVBz3RI40MgYX0P1jhL2ICz00B2VbJDF3');

// Dodaj stripe do window aby był dostępny globalnie
window.stripe = stripe;

// App State
let currentUser = null;
let userHasAccess = false;
let userEnrollments = [];

// Subject Data
const subjects = {
    1: { title: 'Kinematyka', paymentLink: 'https://buy.stripe.com/bJe14o8MJ7Nof90f1N0ZW07', videoId: '', pdfs: [], quiz: [], instructions: 'Instrukcje do kursu Kinematyka...', pdfUrl: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%203/Kinematyka%20ETAP%203.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvS2luZW1hdHlrYSBFVEFQIDMucGRmIiwiaWF0IjoxNzU1ODc2NzIwLCJleHAiOjE3ODc0MTI3MjB9.IM7mawDlPrUuPc2-MdE4vaiHuyAZfGSx4zmpEFjH-IY', pdfUrlEtap1: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%201/Kinematyka%20ETAP%201.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDEvS2luZW1hdHlrYSBFVEFQIDEucGRmIiwiaWF0IjoxNzU2MjQ3ODg5LCJleHAiOjE3ODc3ODM4ODl9.7sXGCVIrfInPJnvZ_nzIhn8jUh1gy2zGYPTY6eX8ERo' },
    2: { title: 'Dynamika', paymentLink: 'https://buy.stripe.com/aFacN66EB9Vwd0S7zl0ZW08', videoId: '', pdfs: [], quiz: [], instructions: 'Instrukcje do kursu Dynamika...', pdfUrl: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%203/Dynamika%20ETAP%203.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvRHluYW1pa2EgRVRBUCAzLnBkZiIsImlhdCI6MTc1NTg3NjA4MCwiZXhwIjoxNzg3NDEyMDgwfQ.VkTbDPnR_jsynn8kld-nL1FLNDhiPAvcgwCTxixAHdA', pdfUrlEtap1: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%201/Dynamika%20ETAP%201.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDEvRHluYW1pa2EgRVRBUCAxLnBkZiIsImlhdCI6MTc1NjI0NzgxNywiZXhwIjoxNzg3NzgzODE3fQ.yPHFswlvpITb9tElgYDVQ-7uICUAuSGETnQGrTd2PcI' },
    3: { title: 'Praca moc energia', paymentLink: 'https://buy.stripe.com/6oU4gA5AxaZAf90f1N0ZW09', videoId: '', pdfs: [], quiz: [], instructions: 'Instrukcje do kursu Praca moc energia...', pdfUrl: null, pdfUrlEtap1: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%201/Praca%20moc%20energia%20ETAP%201.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDEvUHJhY2EgbW9jIGVuZXJnaWEgRVRBUCAxLnBkZiIsImlhdCI6MTc1NjI0Nzk3NiwiZXhwIjoxNzg3NzgzOTc2fQ.X0N52lSDGJv4jqX_6fz_APkC1E4NH67A_zPvhlnJwbI' },
    4: { title: 'Bryła sztywna', paymentLink: 'https://buy.stripe.com/9B6aEYgfb8RsaSK6vh0ZW0a', videoId: '', pdfs: [], quiz: [], instructions: 'Instrukcje do kursu Bryła sztywna...', pdfUrl: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%203/Bryla%20Sztywna%20ETAP%203.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvQnJ5bGEgU3p0eXduYSBFVEFQIDMucGRmIiwiaWF0IjoxNzU1ODc2MDYzLCJleHAiOjE3ODc0MTIwNjN9.dD6MgRIiOwW94CvEqbEeX4ihbSnFe1EQyAmIzZzpacc', pdfUrlEtap1: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%201/Bryla%20Sztywna%20ETAP%201.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDEvQnJ5bGEgU3p0eXduYSBFVEFQIDEucGRmIiwiaWF0IjoxNzU2MjQ3ODA3LCJleHAiOjE3ODc3ODM4MDd9.7Wyz9EnFRcB2SrREwJCXIQWrh041lffGLx7QZZon5Ow' },
    5: { title: 'Ruch drgający', paymentLink: 'https://buy.stripe.com/5kQ28sbYV2t4d0S1aX0ZW0h', videoId: '', pdfs: [], quiz: [], instructions: 'Instrukcje do kursu Ruch drgający...', pdfUrl: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%203/Ruch%20Drgajacy%20ETAP%203.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvUnVjaCBEcmdhamFjeSBFVEFQIDMucGRmIiwiaWF0IjoxNzU1ODc2NzQwLCJleHAiOjE3ODc0MTI3NDB9.tvx_H5jXDIwNY-yODqJUXsE4G13JEVYIlW_Lb4iR5Wo', pdfUrlEtap1: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%201/Ruch%20drgajacy%20ETAP%201.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDEvUnVjaCBkcmdhamFjeSBFVEFQIDEucGRmIiwiaWF0IjoxNzU2MjQ3OTMxLCJleHAiOjE3ODc3ODM5MzF9.7-YnUoIiCkZf_wMpQXffUKJHWs4IehITNK7QxXUVKWU' },
    6: { title: 'Grawitacja i astronomia', paymentLink: 'https://buy.stripe.com/9B6aEYgfb8RsaSK6vh0ZW0b', videoId: '', pdfs: [], quiz: [], instructions: 'Instrukcje do kursu Grawitacja i astronomia...', pdfUrl: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%203/Grawitacja%20i%20astronomia%20ETAP%203.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvR3Jhd2l0YWNqYSBpIGFzdHJvbm9taWEgRVRBUCAzLnBkZiIsImlhdCI6MTc1NTg3NjY5NSwiZXhwIjoxNzg3NDEyNjk1fQ.cl10TVHi-EmsLyJ6HPDOY4nJM4vnxC6bwpmgb4HHJIc', pdfUrlEtap1: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%201/Grawitacja%20i%20astronomia%20ETAP%201.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDEvR3Jhd2l0YWNqYSBpIGFzdHJvbm9taWEgRVRBUCAxLnBkZiIsImlhdCI6MTc1NjI0Nzg1OCwiZXhwIjoxNzg3NzgzODU4fQ.rb-6HpS_XrN3SPl0axr1x611m2i7jIJe1doQTUoVtXk' },
    7: { title: 'Hydrostatyka', paymentLink: 'https://buy.stripe.com/9B6aEYgfb8RsaSK6vh0ZW0c', videoId: '', pdfs: [], quiz: [], instructions: 'Instrukcje do kursu Hydrostatyka...', pdfUrl: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%203/Hydrostatyka%20ETAP%203.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvSHlkcm9zdGF0eWthIEVUQVAgMy5wZGYiLCJpYXQiOjE3NTU4NzY3MDMsImV4cCI6MTc4NzQxMjcwM30.mAJcEJkGNaNlqKVBu6aWPHFYjp18ULn047zCZYMiF6k', pdfUrlEtap1: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%201/Hydrostatyka%20ETAP%201.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvSHlkcm9zdGF0eWthIEVUQVAgMS5wZGYiLCJpYXQiOjE3NTYyNDc4NjcsImV4cCI6MTc4Nzc4Mzg2N30.rbNcqpsKxMtCH9gl1hhszuGSppHp2Khu8IYP1j8Cm7Y' },
    8: { title: 'Termodynamika', paymentLink: 'https://buy.stripe.com/9B6aEYgfb8RsaSK6vh0ZW0d', videoId: '', pdfs: [], quiz: [], instructions: 'Instrukcje do kursu Termodynamika...', pdfUrl: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%203/Termodynamika%20ETAP%203.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvVGVybW9keW5hbWlrYSBFVEFQIDMucGRmIiwiaWF0IjoxNzU1ODc2NzUwLCJleHAiOjE3ODc0MTI3NTB9.8rGD_9RC61HCg2oSW7dDrFUL3i0wuVzg-4rNJdH0piA', pdfUrlEtap1: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%201/Termodynamika%20ETAP%201.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvVGVybW9keW5hbWlrYSBFVEFQIDEucGRmIiwiaWF0IjoxNzU2MjQ3OTM4LCJleHAiOjE3ODc3ODM5Mzh9.MNwrhOhXJk_h6Yt0ndmi1ZRUyNH-mCSESBGRI4kPKMU' },
    9: { title: 'Elektrostatyka', paymentLink: 'https://buy.stripe.com/9B6aEYgfb8RsaSK6vh0ZW0e', videoId: '', pdfs: [], quiz: [], instructions: 'Instrukcje do kursu Elektrostatyka...', pdfUrl: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%203/Elektrostatyka%20ETAP%203.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvRWxla3Ryb3N0YXR5a2EgRVRBUCAzLnBkZiIsImlhdCI6MTc1NTg3NjA5NSwiZXhwIjoxNzg3NDEyMDk1fQ.XWj-KCCNDiWPgi16zTnJZg_Qiw2Y1S2eh9ZbJlhdO8M', pdfUrlEtap1: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%201/Elektrostatyka%20ETAP%201.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDEvRWxla3Ryb3N0YXR5a2EgRVRBUCAxLnBkZiIsImlhdCI6MTc1NTg3NjgyOCwiZXhwIjoxNzg3NzgzODI4fQ.RiTK7yHQ5y1HWYM-ShkW7aVkN0A3NnCDCCEoc2Zl4rE' },
    10: { title: 'Prąd elektryczny', paymentLink: 'https://buy.stripe.com/9B6aEYgfb8RsaSK6vh0ZW0f', videoId: '', pdfs: [], quiz: [], instructions: 'Instrukcje do kursu Prąd elektryczny...', pdfUrl: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%203/Prad%20elektryczny%20ETAP%203.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvUHJhZCBlbGVrdHJ5Y3pueSBFVEFQIDMucGRmIiwiaWF0IjoxNzU1ODc2NzM1LCJleHAiOjE3ODc0MTI3MzV9.s7VVkZCTZRHoFv_Oup5mhxSg-gJhqMeHnBgOOw8UX7k', pdfUrlEtap1: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%201/Prad%20elektryczny%20ETAP%201.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDEvUHJhZCBlbGVrdHJ5Y3pueSBFVEFQIDEucGRmIiwiaWF0IjoxNzU2MjQ3OTE0LCJleHAiOjE3ODc3ODM5MTR9.7zAamhV-HaxMVnpoEh6MSmDRhWm9tHowcuPV8tj-DVg' },
    11: { title: 'Magnetyzm', paymentLink: 'https://buy.stripe.com/9B6aEYgfb8RsaSK6vh0ZW0g', videoId: '', pdfs: [], quiz: [], instructions: 'Instrukcje do kursu Magnetyzm...', pdfUrl: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%203/Magnetyzm%20ETAP%203.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvTWFnbmV0eXptIEVUQVAgMy5wZGYiLCJpYXQiOjE3NTU4NzY3MzAsImV4cCI6MTc4NzQxMjczMH0.-lcmxxpfCkuItbf_OkqhIQvrJEqpf_0eXen6WKFN67w', pdfUrlEtap1: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%201/Magnetyzm%20ETAP%201.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDEvTWFnbmV0eXptIEVUQVAgMS5wZGYiLCJpYXQiOjE3NTYyNDc5MDIsImV4cCI6MTc4Nzc4MzkwMn0.EPo6v5La_BvTCjMfYk8pEVpSHKbBOeL1YExOfoh8ROA' },
    12: { title: 'Indukcja', paymentLink: 'https://buy.stripe.com/9B6aEYgfb8RsaSK6vh0ZW0h', videoId: '', pdfs: [], quiz: [], instructions: 'Instrukcje do kursu Indukcja...', pdfUrl: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%203/Indukcja%20ETAP%203.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvSW5kdWtjamEgRVRBUCAzLnBkZiIsImlhdCI6MTc1NTg3NjcwOSwiZXhwIjoxNzg3NDEyNzA5fQ._YvLNEN_P-qD-k8_Cfk072kwR7vadVJ8DHQnt3mvZKg', pdfUrlEtap1: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%201/Indukcja%20ETAP%201.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvSW5kdWtjamEgRVRBUCAxLnBkZiIsImlhdCI6MTc1NjI0Nzg3NCwiZXhwIjoxNzg3NzgzODc0fQ.EOuKnhPXUR7SuFLGKglOBXskRAaiDO3isO-mJDsswMM' },
    13: { title: 'Fale mechaniczne', paymentLink: 'https://buy.stripe.com/9B6aEYgfb8RsaSK6vh0ZW0i', videoId: '', pdfs: [], quiz: [], instructions: 'Instrukcje do kursu Fale mechaniczne...', pdfUrl: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%203/Fale%20mechaniczne%20ETAP%203.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvRmFsZSBtZWNoYW5pY3puZSBFVEFQIDMucGRmIiwiaWF0IjoxNzU1ODc2MTYxLCJleHAiOjE3ODc0MTIxNjF9.-Hcj2gxw-k7Jrd7Hhs4e4JTnVmtoNOgRhQj_z2vBFJk', pdfUrlEtap1: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%201/Fale%20mechaniczne%20ETAP%201.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDEvRmFsZSBtZWNoYW5pY3puZSBFVEFQIDEucGRmIiwiaWF0IjoxNzU2MjQ3ODQ2LCJleHAiOjE3ODc3ODM4NDZ9.RXwKUXoDtf02WBbReswfWMAp71RsAHjvbCaIzfVPRfc' },
    14: { title: 'Fale elektromagnetyczne', paymentLink: 'https://buy.stripe.com/9B6aEYgfb8RsaSK6vh0ZW0j', videoId: '', pdfs: [], quiz: [], instructions: 'Instrukcje do kursu Fale elektromagnetyczne...', pdfUrl: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%203/Fale%20elektromagnetyczne%20ETAP%203.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvRmFsZSBlbGVrdHJvbWFnbmV0eWN6bmUgRVRBUCAzLnBkZiIsImlhdCI6MTc1NTg3NjExNSwiZXhwIjoxNzg3NDEyMTE1fQ.5GgJpn8API7C1CQt1bywzC1Iarpu48YrYQBOZDTOoMc', pdfUrlEtap1: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%201/Fale%20elektromagnetyczne%20ETAP%201.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDEvRmFsZSBlbGVrdHJvbWFnbmV0eWN6bmUgRVRBUCAxLnBkZiIsImlhdCI6MTc1NjI0NzgzNywiZXhwIjoxNzg3NzgzODM3fQ.T1U-Md24kgEAgFh_Uzf1bn2uVCIrP5OckQxU8lze9l0' },
    15: { title: 'Fizyka atomowa', paymentLink: 'https://buy.stripe.com/9B6aEYgfb8RsaSK6vh0ZW0k', videoId: '', pdfs: [], quiz: [], instructions: 'Instrukcje do kursu Fizyka atomowa...', pdfUrl: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%203/Atomowa%20ETAP%203.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvQXRvbW93YSBFVEFQIDMucGRmIiwiaWF0IjoxNzU1ODc1OTczLCJleHAiOjE3ODc0MTE5NzN9.BGinXG0-1f8o5YALJqZ6c8Doy4WwSxlHHG3Vfb2nW-s', pdfUrlEtap1: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%201/Atomowa%20ETAP%201.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDEvQXRvbW93YSBFVEFQIDEucGRmIiwiaWF0IjoxNzU2MjQ3Nzk2LCJleHAiOjE3ODc3ODM3OTZ9.MpCe3oyOlBDI5E0xc9ARBnPFREkia9FS4Pp4bW-bmy4' },
    16: { title: 'Fizyka jądrowa i relatywistyka', paymentLink: 'https://buy.stripe.com/9B6aEYgfb8RsaSK6vh0ZW0l', videoId: '', pdfs: [], quiz: [], instructions: 'Instrukcje do kursu Fizyka jądrowa i relatywistyka...', pdfUrl: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%203/Jadrowa%20i%20relatywistyka%20ETAP%203.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDMvSmFkcm93YSBpIHJlbGF0eXdpc3R5a2EgRVRBUCAzLnBkZiIsImlhdCI6MTc1NTg3NjcxNiwiZXhwIjoxNzg3NDEyNzE2fQ.F1TjucTCHwD6rUNe_tLzPsXbKN6nzk-2ZScq-l-1H-0', pdfUrlEtap1: 'https://kldekjrpottsqebueojg.supabase.co/storage/v1/object/sign/Etap%201/Jadrowa%20i%20relatywistyka%20ETAP%201.pdf?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MTMzYjY2Ni0wNjU5LTQ0ODgtYWU2MC01MDQ1ODU3ODc0Y2EiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJFdGFwIDEvSmFkcm93YSBpIHJlbGF0eXdpc3R5a2EgRVRBUCAxLnBkZiIsImlhdCI6MTc1NjI0Nzk1MywiZXhwIjoxNzg3NzgzOTUzfQ.LZpy0Ytrd3ooZFryXku6kvcU3z7Awz-Rk4PK-6cMYvw' }
};

// Dodaj subjects do window aby był dostępny globalnie
window.subjects = subjects;

const paymentLinkAllMaterials = 'https://buy.stripe.com/00w00k7IFaZA9OG9Ht0ZW06';
window.paymentLinkAllMaterials = paymentLinkAllMaterials; 